spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dm_local?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lc111
#  datasource:
#    url: jdbc:mysql://172.31.86.145:3306/infoportal?characterEncoding=UTF-8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: vs
#    password: vs#^(369